FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies and ts-node-dev globally
RUN npm install && npm install -g ts-node-dev

COPY . .

EXPOSE 5000

CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]